### PR TITLE
fix: edge case with tabs still scrolling to top

### PR DESCRIPTION
**Pull request by andreialecu**
ref #205

### CODE REVIEW

**Comment by andreialecu** [comment]
Released as 4.5.2

**Comment by Hirbod** [comment]
@andreialecu it's better but still not 100% fixed.

I have 4 tabs (with prop lazy). As soon as the lazy one loads, it syncs all the other screens.
See following video (i have added indexes to the views):

So there is still an edge case to be handled I guess.
https://streamable.com/h184la

**Comment by andreialecu** [comment]
Hey @hirbod, I've been refactoring some things over in #255 and I think this may be fixed. Could you give `react-native-collapsible-tab-view@5.0.0-rc.3` a try?

See the PR above for prerequisites.

**Comment by hirbod** [comment]
Will be able to test this in about 2 hours. Does it also handle the issue that happens on android with numColums on FlatList?

**Comment by andreialecu** [comment]
Not sure, I don't use `numColumns` but it might.

**Comment by hirbod** [comment]
@andreialecu I can tell you that I've upgraded and the first thing I realized is that that new release is breaking the swipe behavior in my view. I can only swipe tabs now when I place my finger on the tabs directly or when I swipe in the header area. 

It does not play nicely with `RectButton` by react-native-gesture-handler anymore. It does work with TouchableOpacity though

**Pull request merged**
