### PR TITLE
feat: small v3 fixes

### PR DESCRIPTION
**Pull request by alexpchin**
feat: ensuring that children is not `undefined`

### CODE REVIEW

**Comment by PedroBern** [comment]
@alexpchin thanks for the PR, but not sure about the need of this. The definition of children is:

```ts
 children: React.ReactElement[]
```

[Here](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/types.ts#L40).

The children are always an array because I didn't see a use-case where we don't have children, or we have only one child. If children are not provided, there is no screen to be rendered. And if we have only one child, there is no need for tabs. Perhaps I'm missing something?

**Comment by PedroBern** [comment]
What do you think about we throwing an error in case we have only one or zero children?

**Comment by alexpchin** [comment]
So whilst unlikely, you might have a scenario where you only have one tab and even more unlikely, undefined.

For example, if you used tabs for a profile page, but a certain user type only had one tab, this would not be an array. It would be more work to create two pages that dealt differently with the header and tabs.

Regarding the undefined, this is really, really unlikely. However, when developing perhaps we throw an error that is more helpful rather than just a crash?

**Comment by PedroBern** [comment]
Yes, I see your point, I agree. I did some changes on #74, let me know your thought

**Comment by PedroBern** [comment]
Closing in favor of #74

**Pull request closed without merging**
