### PR TITLE
fix: tabs should not scroll to top

### LINKED ISSUE #198: Tab switching & state updating causing scroll position issues
Hi there, hope you're all well. Love the library but I'm experiencing two problems at the moment, the latter of which is the most concerning. Would really appreciate the help!

### PROBLEM 1
When navigating between tabs, the scroll position of the inactive tab should persist however this only works if I don't interact with the active tab. When interacting with the active tab, the inactive tab's scroll position returns to 0. This may be expected behaviour, and if so, I'd really appreciate some suggestions!

https://user-images.githubusercontent.com/74291167/131118051-16a17ac9-6f15-4123-8cdb-566e2e481ad4.mp4

### PROBLEM 2
When there's a state change, the inactive tab's scroll position matches the current scroll position of the active tab. Very strange occurrence.

https://user-images.githubusercontent.com/74291167/131118066-3d424b3f-6295-4e45-ab49-80fc2531abae.mp4

### CODE

```javascript
import { Button, StyleSheet, View } from "react-native";
import React, { useState } from "react";

import { Tabs } from "react-native-collapsible-tab-view";

const CollapsibleTabs = () => {
  const [count, setCount] = useState(0);

  return (
    <View style={styles.container}>
      <View style={styles.button}>
        <Button
          title={`Update State: ${count}`}
          onPress={() => setCount(count + 1)}
        />
      </View>
      <Tabs.Container renderHeader={Header} >
        <Tabs.Tab name="One">
          <Tabs.ScrollView>
            <Page />
          </Tabs.ScrollView>
        </Tabs.Tab>
        <Tabs.Tab name="Two">
          <Tabs.ScrollView>
            <Page />
          </Tabs.ScrollView>
        </Tabs.Tab>
      </Tabs.Container>
    </View>
  );
};

const Header = (props) => {
  return <View {...props} style={styles.header} />
}

const Page = () => {
  return (
    <View style={styles.page}>
      <View style={{ width: 50, height: 50, backgroundColor: "green" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "blue" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "purple" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "violet" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "pink" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "red" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "orange" }} />
      <View style={{ width: 50, height: 50, backgroundColor: "yellow" }} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  button: {
    position: "absolute",
    bottom: 30,
    right: 30,
    zIndex: 1
  },
  background: {
    position: "absolute",
    top: 0,
    width: 390,
    height: 390,
  },
  page: {
    width: 390,
    height: 830 * 2,
    backgroundColor: "black",
  },
  header: {
    width: 390,
    height: 390,
    backgroundColor: "pink",
  },
});

export default CollapsibleTabs;

```

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #198

### CODE REVIEW

**Comment by PedroBern** [comment]
@andreialecu I got a bug at first glance on old devices - O don't have this bug on main.


https://user-images.githubusercontent.com/39778068/137044422-48be1c0a-d45d-4bb7-aacf-8a67aaf93429.mp4

**Comment by Hirbod** [comment]
Anything holding back to merge this?

**Comment by andreialecu** [comment]
I've been using this for a while in production and it seems to work fine. I'll merge it.

**Comment by andreialecu** [comment]
Released as 4.5.0

**Comment by Hirbod** [comment]
@andreialecu weird, for me, it is still resetting the scroll position, as soon as I switch the tab.

**Comment by andreialecu** [comment]
Indeed there's an edge case here, it works if the tab you're moving away from is scrolled down a bit, but if one is scrolled to the top, then it will reset the others.

I'll open a subsequent PR to fix this.

**Comment by Hirbod** [comment]
@andreialecu here is a video demonstrating, that this haven't changed anything:
https://streamable.com/wr7mrh

As soon as I change the tab, my previous view will scroll to top, which is pretty annoying, because I would love to maintain the scroll position (which is also pretty important for FlatList performance, as it currently retriggers all the VirzualizedList events)

**Comment by Hirbod** [comment]
For me, it only works, when every lazy loaded tab was loaded and I scrolled within every single one of them once.

**Comment by andreialecu** [comment]
@Hirbod https://github.com/PedroBern/react-native-collapsible-tab-view/pull/230 should fix it, it was just released as 4.5.2

**Comment by Hirbod** [comment]
@andreialecu it's better but still not 100% fixed.

I have 4 tabs (with prop lazy). As soon as the lazy one loads, it syncs all the other screens.
See following video (i have added indexes to the views):

So there is still an edge case to be handled I guess.
https://streamable.com/h184la

**Comment by andreialecu** [comment]
I'm not able to reproduce this. See this recording from the example app:

https://user-images.githubusercontent.com/697707/149623449-172d9b8a-783b-4de5-bc2c-3b6c0f73aff4.mov

**Comment by Hirbod** [comment]
Sorry, here is the updated video. 
https://streamable.com/vk9n8t

**Comment by andreialecu** [comment]
Oh, ok, I see now.

**Comment by Hirbod** [comment]
@andreialecu And there is another edge case. It will restore all scroll positions to top as soon as I fully scroll up (uncollapsing the header)
https://streamable.com/b1bug4

Would be wonderful if you could fix those last two remaining little bugs, then this lib is perfect :D

**Comment by Hirbod** [comment]
@andreialecu did you had a chance to have a last look at the issue? Putting $50 bounty on it!

**Comment by hirbod** [comment]
@andreialecu any chance?

**Comment by andreialecu** [comment]
> @andreialecu And there is another edge case. It will restore all scroll positions to top as soon as I fully scroll up (uncollapsing the header) [streamable.com/b1bug4](https://streamable.com/b1bug4)
> 
> Would be wonderful if you could fix those last two remaining little bugs, then this lib is perfect :D

If one tab is at the top, with the header revealed, then if you switch to a different tab then the header is still revealed, and it only makes sense to be scrolled to the top in that tab as well.

 If that didn't happen, the flatlist would look glitched. I'm not entirely sure what you'd expect to happen here, care to elaborate?

**Comment by hirbod** [comment]
@andreialecu I agree with the last edge case, more likely I am still stumbling across this bug:



> Sorry, here is the updated video. https://streamable.com/vk9n8t
> 
> You can cleary see, the second tab 3 got rendered, tab 1 and tab 2 had the same indexes at top (like the third one coming in). Same happens when the 4th tab renderes. After that, the sync works fine.

**Comment by andreialecu** [comment]
Are you able to reproduce this in the example app that comes with this repository? If you can, can you share a video that shows it on the example app?

**Comment by hirbod** [comment]
I'll need to set it up. Will get back to you after its running on my device

**Pull request merged**
