### PR TITLE
Fix ensure array children

### LINKED ISSUE #68: Ensure that children exists
In `createCollapsibleTabs`, we should ensure that children exists as this can be `undefined`:

Line 88:

```ts
const scrollY = useSharedValue([...new Array(children.length)].map(() => 0));
```

Line 106:

```ts
const [data] = React.useState(
  [...new Array(children.length)].map((_, i) => i)
)
```

### LINKED ISSUE #72: Two children with the same key `undefined` In a Bare React Native App
I'm seeing the error:

```
Warning: Encountered two children with the same key, `undefined`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### PR DESCRIPTION
**Pull request by PedroBern**
an alternative to #69 

@alexpchin  what you think?

Close #72
Close #68

[documentation](https://reactjs.org/docs/react-api.html#reactchildrentoarray)

```jsx
// add unique key to each child
React.Children.toArray(children)
```

### CODE REVIEW

**Comment by alexpchin** [comment]
@PedroBern 

I'm liking this. However, this is still saying that there has to be more than one element in children? 

Another example where there might only be one child is. potentially, is if someone wanted to use this package to render a header with the snap, or diffClamp but without a TabBar - perhaps a Searchbox ontop of results?  If we allow one child, then they can re-use the same page structure in the app as a page with more than one tab?

I personally have a use-case in my app (which I know is unusual) where there are multiple user types but the most basic only has one tab as they don't have enough content. However, because of the way the profile page is structured (like Instagram), the user's profile image and details are rendered above the tabs?

**Comment by PedroBern** [comment]
> I'm liking this. However, this is still saying that there has to be more than one element in children?

No, it accepts 1 or more 👍 

```jsx
if (React.Children.count(children) === 0) {
  throw new Error('CollapsibleTabs must have at least one child.')
}
```

**Comment by alexpchin** [comment]
Have you run the Default example and commented out the everything apart from Articles? (Or just leave any other one).

**Comment by PedroBern** [comment]
yes you are right, it throws an error with only 1 child! I will investigate now

**Comment by PedroBern** [comment]
@alexpchin now it's working the problem was with the indicator component.

**Comment by alexpchin** [comment]
I've just pulled the latest version. However, I currrently see:

Screenshot 2021-01-30 at 21 52 37

With the type error being: 

```
(property) Container: React.FC<CollapsibleProps<TabNames, MaterialTabBarProps<TabNames>>>
This JSX tag's 'children' prop expects type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>[] | ... 6 more ... | (ReactElement<...>[] & ReactPortal)' which requires multiple children, but only a single child was provided.ts(2745)
```

And: 

Screenshot 2021-01-30 at 21 57 14

Is it working for you?

**Comment by PedroBern** [comment]
here is working, but there is this typescript error, I will fix now

WhatsApp Image 2021-01-30 at 19 38 11

**Comment by PedroBern** [comment]
I was having this error before, maybe you are not with the latest version, I rebased and forced push

**Comment by PedroBern** [comment]
@alexpchin just rebased and for push again

**Comment by PedroBern** [comment]
I merged, if you see any errors, let me know

**Pull request merged**
