### PR TITLE
test: add test setup

### LINKED ISSUE #81: Automated tests
### Feature request

It would be great if a test suite could verify that everything is working properly. The interactions are pretty finicky and things can break in odd places by doing minor changes in others.

This would make the library much more maintainable and easier to refactor in the future, while giving more peace of mind to users that upgrades are safe.

Should be relatively easy to add gray box e2e testing using:
https://github.com/wix/Detox

Tests could be added to initiate scrolls and touches, then assert whether things are positioned correctly.

Another possibility is to convert the Example app to use Storybook:
https://storybook.js.org/
https://www.learnstorybook.com/intro-to-storybook/react-native/en/get-started/

It would then be possible to use loki to do screenshot diff testing for the stories:
https://github.com/oblador/loki

### PR DESCRIPTION
**Pull request by PedroBern**
Closes #81 

Tests are not working, because it's mocking the reanimated, which is essential to exist in the tests 🤔

### CODE REVIEW

**Comment by andreialecu** [comment]
Is this the right approach though? It wouldn't test actual on-device interaction which is what we'd be after here. 🤔  [Detox](https://github.com/wix/detox) on the other hand would do it.

**Comment by PedroBern** [comment]
> Is this the right approach though?

No. Jest needs Reanimated to be mocked. We need Reanimated to test the app.

> Detox on the other hand would do it.

Yes we need to add detox or appium. I have no experience with any of them, but detox seems a better option since it's RN focused.

What would be the best approach? Some consideration points, please correct me if I'm wrong:

- Adding detox will need to build the app before the tests.
- Tests can be added to the example folder, and leverage the expo app to make the builds
- Adding tests into the example folder will need to resolve the components outside the node_modules (../src)
- CircleCI offers a little macOS free tier to run an iOS simulator (I already requested to my account), not sure if the free tier is enough
- On the other hand, testing on android is cheaper (Linux)
- Question: After running the app on simulator, we can use jest to test without mocking Reanimated?

What am I missing?

**Comment by andreialecu** [comment]
I have some experience with Detox. It's not hard to add and work with.

In my experience, CircleCI cannot run Android emulators, just iOS: https://support.circleci.com/hc/en-us/articles/360000028928-Testing-with-the-Android-emulator-on-CircleCI

I do have a project that runs Detox on CircleCI with iOS though, and it runs properly.

When I did my initial research on Appium vs Detox, I found a lot of issues with Appium which were a non-starter. I don't remember what they were exactly, but I don't recommend it.

Detox can just be added as a script to package.json:

```
    "test": "detox test -c ios.sim.debug main.spec.js",
```

Running `yarn test` then spawns the iOS simulator, runs the test, and closes it. It's pretty simple.

**Comment by andreialecu** [comment]
Note that the above comment refers to using detox with vanilla react-native (not expo).

Expo may make things easier: https://blog.expo.io/testing-expo-apps-with-detox-and-react-native-testing-library-7fbdbb82ac87

**Comment by PedroBern** [comment]
> Expo may make things easier: https://blog.expo.io/testing-expo-apps-with-detox-and-react-native-testing-library-7fbdbb82ac87

Nice article. Indeed looks pretty straightforward. I will dig more into this once I'm able to run on iOS, so I can test locally, then try on circleCI. Up to 2 more weeks until my m1 arrives 🎉   If you need these tests to use with confidence on your project and want to take ahead it's ok for me, I will follow closely.

**Comment by andreialecu** [comment]
I think you can test locally on Android with Detox as well.

**Comment by PedroBern** [comment]
> I think you can test locally on Android with Detox as well.

I do not want to be boring, but my computer is bad, I am waiting for the upgrade to run any simulator. I have developed only on the real devices.

**Comment by andreialecu** [comment]
Ah, makes sense. I see.

**Comment by andreialecu** [comment]
Note that it may be possible to run it on a real Android device: https://github.com/wix/Detox/issues/968

**Comment by PedroBern** [comment]
That's nice, I will look into it later :)

**Comment by alexpchin** [comment]
@PedroBern @andreialecu I have some experience with detox FYI. I would choose detox over Apium personally. I can help with this once I have fixed the current issues and release the latest build of the app I am working on.

**Comment by PedroBern** [comment]
@alexpchin thanks, all help is welcome 🙌

**Comment by shail-spreadd** [comment]
@PedroBern i am getting error while writing test cases using jest 
Can you please help me? my timeline is on monday and i need to complete the test cases for this package

``` The above error occurred in the <ForwardRef> component:
    
    node_modules/react-native-collapsible-tab-view/lib/commonjs/Container.tsx:65:9
    ```
    
jest.setup.js

    ```global.__reanimatedWorkletInit = () => {};
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock')
);```

**Comment by andreialecu** [comment]
@shail-spreadd please open a new issue.

**Pull request closed without merging**
