### PR TITLE
fix: rework contentHeights to use a shared value

### LINKED ISSUE #145: Content jumping as you scroll down
### Current behavior

As I'm scrolling down a `Tab.FlatList`, I'm seeing small content adjustments happening. Please see the attached video.

[simulator1.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/6037367/simulator1.mov.zip)

This is on a bare react-native app.

### Expected behaviour

The scroll should be smooth.

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #145

### CODE REVIEW

**Comment by andreialecu** [comment]
@alexpchin please give this a try:

[react-native-collapsible-tab-view-v4.0.0.tgz.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/6042730/react-native-collapsible-tab-view-v4.0.0.tgz.zip)

**Comment by alexpchin** [comment]
Thanks for the assist @andreialecu I'll just installed it seems to fix the issue. 

Just a note, I was previously on `^4.0.0-rc.11` so this zip broke my CenteredEmptyList implementation (as per the example code) as `useTabsContext` is not exported. I can update to `useHeaderMeasurements` but the example will need to be updated too I believe?

**Comment by andreialecu** [comment]
Fixed the example in [`9419228` (#146)](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/146/commits/9419228138e251eec7c8d4254da80853ad8e4136)

**Comment by andreialecu** [comment]
Released as 4.0.1

**Pull request merged**
