### PR TITLE
feat: removing duplicate pagerOpacity.value change

### PR DESCRIPTION
**Pull request by alexpchin**
Fix for #148

### CODE REVIEW

**Comment by andreialecu** [comment]
It seems odd that this would make any difference, it's being set to `1`, which means `100%`. Even if there's a race condition, the result should still be that it's set to `100%` opacity.

🤔

**Comment by andreialecu** [comment]
The change in this PR actually breaks the dynamic tabs example.

**Comment by alexpchin** [comment]
If you also remove line 176.

```
if (!firstRender.current) pagerOpacity.value = 0
```

Then the example works.

Removing a tab gives `scrollToIndex out of range: requested index 1 but maximum is 0`. However, I think this was happening before these changes?

**Comment by alexpchin** [comment]
I think it is ok?

**Comment by andreialecu** [comment]
> If you also remove line 176.

That would be incorrect. The fade is on purpose otherwise the scroll position will jump around while the tabs are recreated. This is more visible on Android while the scrollview is slightly scrolled down so that only part of the header is visible.

`withTiming(1)` if the starting opacity is `1` shouldn't do anything. It's supposed to start from the existing value and transition to the new value.

I don't see how the fade can result in this problem, I suspect it's somewhere else. Without an actual repro I can see it's hard to verify though.

**Comment by andreialecu** [comment]
Closing, feel free to ping us to reopen if this is still an issue.

**Comment by alexpchin** [comment]
Hi @andreialecu No need to re-open this PR however, as per #148 I do still see that the page opacity sometimes doesn't turn to 1 when headerHeight isn't set.

My workaround at the moment is to set the `headerHeight` to 1, it is then re-calculated. This can cause some layout jumps but it does seem to stop the opacity problem.

**Pull request closed without merging**
